
import { Language, Translation } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  [Language.ENGLISH]: {
    appName: 'MedRush',
    startCare: 'Start Care',
    chooseLanguage: 'Choose Preferred Language',
    whoAreYou: 'Who are you?',
    patient: 'Patient',
    caretaker: 'Caretaker',
    nurse: 'Nurse',
    login: 'Login',
    name: 'Full Name',
    phone: 'Phone Number',
    otp: 'OTP Verification',
    verify: 'Verify & Login',
    hospital: 'Hospital Name',
    uploadPrescription: 'Upload or Scan Prescription',
    scanning: 'AI Analyzing Prescription...',
    readAloud: 'Read Aloud',
    callReminder: 'AI Call Reminder',
    addRelative: 'Add Relative',
    relation: 'Relation (e.g., Father, Mother)',
    patientPhone: 'Patient Phone Number',
    add: 'Add Patient',
    dashboard: 'Dashboard',
    status: 'Status',
    missed: 'Missed',
    taken: 'Taken',
    pending: 'Pending',
    summaryTitle: 'Prescription Summary',
    noCaretakerAlert: '🚨 Patient has no caretaker! Nurse Alert Triggered.'
  },
  [Language.TELUGU]: {
    appName: 'మెడ్రష్',
    startCare: 'కేర్ ప్రారంభించండి',
    chooseLanguage: 'భాషను ఎంచుకోండి',
    whoAreYou: 'మీరు ఎవరు?',
    patient: 'రోగి',
    caretaker: 'సంరక్షకుడు',
    nurse: 'నర్స్',
    login: 'లాగిన్',
    name: 'పూర్తి పేరు',
    phone: 'ఫోన్ నంబర్',
    otp: 'OTP ధృవీకరణ',
    verify: 'ధృవీకరించండి & లాగిన్',
    hospital: 'ఆసుపత్రి పేరు',
    uploadPrescription: 'ప్రిస్క్రిప్షన్ అప్‌లోడ్ లేదా స్కాన్ చేయండి',
    scanning: 'AI ప్రిస్క్రిప్షన్‌ను విశ్లేషిస్తోంది...',
    readAloud: 'చదివి వినిపించండి',
    callReminder: 'AI కాల్ రిమైండర్',
    addRelative: 'బంధువును చేర్చండి',
    relation: 'సంబంధం (ఉదా: తండ్రి, తల్లి)',
    patientPhone: 'రోగి ఫోన్ నంబర్',
    add: 'రోగిని చేర్చండి',
    dashboard: 'డ్యాష్‌బోర్డ్',
    status: 'స్థితి',
    missed: 'తప్పింది',
    taken: 'తీసుకున్నారు',
    pending: 'వేచి ఉంది',
    summaryTitle: 'ప్రిస్క్రిప్షన్ సారాంశం',
    noCaretakerAlert: '🚨 రోగికి సంరక్షకుడు లేరు! నర్స్ అలర్ట్ ప్రారంభమైంది.'
  },
  [Language.HINDI]: {
    appName: 'मेडरश',
    startCare: 'देखभाल शुरू करें',
    chooseLanguage: 'अपनी पसंदीदा भाषा चुनें',
    whoAreYou: 'आप कौन हैं?',
    patient: 'मरीज',
    caretaker: 'देखभाल करने वाला',
    nurse: 'नर्स',
    login: 'लॉगिन',
    name: 'पूरा नाम',
    phone: 'फ़ोन नंबर',
    otp: 'ओटीपी सत्यापन',
    verify: 'सत्यापित करें और लॉगिन',
    hospital: 'अस्पताल का नाम',
    uploadPrescription: 'नुस्खा अपलोड या स्कैन करें',
    scanning: 'AI नुस्खे का विश्लेषण कर रहा है...',
    readAloud: 'पढ़कर सुनाएं',
    callReminder: 'AI कॉल रिमाइंडर',
    addRelative: 'रिश्तेदार जोड़ें',
    relation: 'संबंध (जैसे पिता, माता)',
    patientPhone: 'मरीज का फ़ोन नंबर',
    add: 'मरीज जोड़ें',
    dashboard: 'डैशबोर्ड',
    status: 'स्थिति',
    missed: 'छूट गया',
    taken: 'ले लिया',
    pending: 'लंबित',
    summaryTitle: 'नुस्खा सारांश',
    noCaretakerAlert: '🚨 मरीज का कोई देखभाल करने वाला नहीं है! नर्स अलर्ट जारी।'
  }
};
